### ISSUE TITLE
Evaluation and MCO runner data are entangled

### ISSUE THREAD

**Issue by corranwebster** [force-h2020/force-bdss#212]
Currently we have entanglement in the `Workflow` between information which is needed to evaluate at a data point (parameters, kpis, and execution layers) and information which is required to drive the MCO process (communicators, notifiers, ui_hooks, but also parameters and kpis).

It would be good to factor out the bits required for execution into an object (this is the primary thing being edited in the workflow manager GUI), the information needed for communicating with the MCO within an individual execution, and the information that the MCO runner needs.

This would be a fairly major design change, but would simplify a lot of code.  It should be done with care if it is done at all.

**Comment by flongford** [comment]
From what I can tell, this is mainly because the `BaseMCO` class does not enforce the user to implement any specific operation during its `run` method. Therefore, even though both the `EvaulateOperation` and `OptimizeOperation` classes provide a standardised way of performing an MCO process, there is plenty of room for redundency between each feature. 

Additionally, both are currently independent of each other, even though the functionalities in `EvaluateOperation` could contribute to `OptimizeOperation`. In fact, most of our `BaseMCO` subclasses do not use the `EvaluateOperation ` class (and therefore the `MCOCommunicator` class), and implement their own single point evaluator during an MCO run.

**Comment by flongford** [comment]
We could solve this by passing in an object that contains all workflow related references and performs a generic function that calculates the state of a given `Workflow` for a set of provided parameter values.
