### ISSUE TITLE
Workflow object can implement (de)serialization

### ISSUE THREAD

**Issue by Corwinpro** [force-h2020/force-bdss#264]
[`Workflow` class](https://github.com/force-h2020/force-bdss/blob/f3743081d049eb7d1874e05b06b96ba4110ec7a0/force_bdss/core/workflow.py#L26) doesn't implement (de)serialization methods of itself into a json-compatible format, as well as can't create a complete instance of itself given a nested dictionary.

Currently, the `WorkflowReader` and `WorkflowWriter` classes are responsible for doing that. They seem to be separated from the `Workflow` class, despite that their area of responsibility is only to parse the `Workflow`-related data files.

We can consider refactoring this unnecessary separation of responsibilities, and move the `read` / `write` methods from `WorkflowReader` and `WorkflowWriter` to `Workflow`.

**Comment by Corwinpro** [comment]
@flongford What do you think about this? Does this issue make sense?

**Comment by flongford** [comment]
> @flongford What do you think about this? Does this issue make sense?

This makes sense - after chatting offline, we decided to implement a `__get_state__` method to the `Workflow` class that extracts all information of an instance into a dictionary containing basic python objects. 

This information should be able to be passed directly into the `__init__` method of the same class to create another instance possessing equivalent information.

The `WorkflowWriter` and `WorkflowReader` classes are then only used to save or load file objects in a certain format, rather than determining how the state of a `Workflow` instance is represented.

**Comment by Corwinpro** [comment]
FYI: every `ContributedUI` class must ensure there is a version key in the `workflow_data` attribute. This will indicate the workflow data json version.
