### ISSUE TITLE
Express what kind of input data is needed by the datasources

### ISSUE THREAD

**Issue by martinRenou** [force-h2020/force-bdss#46]
We need to express what kind of input data (data driven by the MCO or given by the user) is needed for the datasources. For example if we have a data source which needs a username and password in order to have access to a database, and some other data (e.g. viscosity, compound...), we want the username and password given by the user, and we want to be able to express that the viscosity CAN be driven by the MCO.

![20170725_163616](https://user-images.githubusercontent.com/21197331/28581027-10485936-7159-11e7-8dd1-62dbccf5709c.jpg)

**Comment by stefanoborini** [comment]
We should give a "slots" method to data sources. It will accept the model (because slots may depend on configuration options) and will return the input slots and the output slots that are required for the data source to perform its task. Slots will have a cuba type (and dimensionality?)

When it is time to execute the data source, some of these slots will be satisfied from the MCO parameters. Some of them will be satisfied by other data sources (and we will have to deal with dependencies in evaluation). Some of them will be resolved by the model (e.g. the user hardcoded the slot value). In the first two cases, we will have to specify the name of the variables from which to extract the slot values.

**Comment by stefanoborini** [comment]
Fixed in #69
